name: CI/CD

# SPDX-License-Identifier: MIT
# Copyright (c) 2026 WinQuicEcho contributors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      build_dir: build
      config: Release
      artifact_name: build-artifacts

  test:
    needs: build
    uses: ./.github/workflows/reusable-test.yml
    with:
      build_dir: build
      config: Release
      artifact_name: build-artifacts

  test-km:
    needs: build
    uses: ./.github/workflows/reusable-test-km.yml
    with:
      build_dir: build
      config: Release
      artifact_name: build-artifacts
